configuration:
  name: DUPA
  host: 127.0.0.1
  port: 9999
  data_interval: 1000
  metadata_interval: 19999
components:
  cpu: true
  memory: true
  netIF: true
  system: true
  proc: true
other:
  debug: true
