monitor-configuration:
  monitorList:
  -
    id: 1
    name: monitor1
    address: https://boiling-refuge-92080.herokuapp.com

spring:
  application:
    index: login.html
  jpa:
    database: POSTGRESQL
    show-sql: false
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    schema: main
    username: postgres
    password: 1qaz@WSX
    driverClassName: org.postgresql.Driver

logging:
  level:
    org.springframework: INFO
    security: DEBUG

server:
     port: 7755